# Generated by Django 6.0.1 on 2026-04-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-joined_at'], 'permissions': [('invite_member', 'Can invite team members'), ('remove_member', 'Can remove team members'), ('update_member_role', 'Can update member roles'), ('delete_team', 'Can delete a team')]},
        ),
    ]
