# Generated by Django 6.0.1 on 2026-05-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_pending_invitation',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('team', 'email', 'status')},
        ),
    ]
