# Generated by Django 6.0.1 on 2026-04-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cvat_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
