# Generated by Django 6.0.1 on 2026-06-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_cvat_project_id'),
        ('teams', '0004_remove_invitation_unique_pending_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='teams.team'),
        ),
    ]
