# Generated by Django 6.0.1 on 2026-04-02 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('starting', 'Starting'), ('active', 'Active'), ('stopping', 'Stopping'), ('error', 'Error')], default='inactive', max_length=50)),
                ('endpoint_url', models.URLField(blank=True)),
                ('auth_token', models.CharField(blank=True, max_length=64)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=100)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inference_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('metric', models.CharField(max_length=100)),
                ('threshold', models.FloatField()),
                ('observed_value', models.FloatField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_alerts', to='deployments.inferenceendpoint')),
            ],
            options={
                'db_table': 'drift_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('format', models.CharField(choices=[('pytorch', 'PyTorch'), ('onnx', 'ONNX'), ('tensorrt', 'TensorRT'), ('tflite', 'TFLite'), ('coreml', 'CoreML')], default='pytorch', max_length=50)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/%Y/%m/')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('training_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entries', to='training.trainingjob')),
            ],
            options={
                'db_table': 'model_registry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inferenceendpoint',
            name='registry_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='deployments.modelregistry'),
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('prediction', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deployments.inferenceendpoint')),
            ],
            options={
                'db_table': 'monitoring_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='monitoring__endpoin_d096a7_idx'), models.Index(fields=['is_flagged'], name='monitoring__is_flag_64f876_idx')],
            },
        ),
    ]
