# Generated by Django 6.0.1 on 2026-04-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inferenceendpoint',
            options={'ordering': ['-created_at'], 'permissions': [('start_endpoint', 'Can start an inference endpoint'), ('stop_endpoint', 'Can stop an inference endpoint')]},
        ),
    ]
