# Generated by Django 6.0.1 on 2026-06-09 06:08

import deployments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_alter_inferenceendpoint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelregistry',
            name='model_file',
            field=models.FileField(blank=True, null=True, storage='core.storage.get_artifacts_storage', upload_to=deployments.models.artifact_upload_path),
        ),
    ]
