# Generated by Django 6.0.1 on 2026-07-16 03:54

import auto_label.models
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_project_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLabelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('family', models.CharField(default='yolo', max_length=100)),
                ('framework', models.CharField(default='ultralytics', max_length=100)),
                ('task_type', models.CharField(choices=[('object_detection', 'Object Detection'), ('instance_segmentation', 'Instance Segmentation')], max_length=50)),
                ('capabilities', models.JSONField(default=list)),
                ('class_names', models.JSONField(blank=True, default=list)),
                ('model_file', models.FileField(storage=core.storage.get_artifacts_storage, upload_to=auto_label.models.auto_label_model_upload_path)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('validating', 'Validating'), ('ready', 'Ready'), ('failed', 'Failed')], default='validating', max_length=20)),
                ('validation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_label_models', to='projects.project')),
            ],
            options={
                'db_table': 'auto_label_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
