# Generated by Django 6.0.1 on 2026-07-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_label', '0001_initial'),
        ('datasets', '0014_datasetimportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLabelDatasetJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(default='bbox', max_length=20)),
                ('confidence', models.FloatField(default=0.25)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('done', models.PositiveIntegerField(default=0)),
                ('labeled_images', models.PositiveIntegerField(default=0)),
                ('saved_annotations', models.PositiveIntegerField(default=0)),
                ('skipped_predictions', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_label_jobs', to='datasets.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_jobs', to='auto_label.autolabelmodel')),
            ],
            options={
                'db_table': 'auto_label_dataset_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
