# Generated by Django 6.0.1 on 2026-04-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-created_at'], 'permissions': [('review_annotation', 'Can review annotations'), ('approve_annotation', 'Can approve annotations')]},
        ),
    ]
