# Generated by Django 6.0.1 on 2026-04-02 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_update_media_and_version'),
        ('projects', '0002_add_owner_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backbone', models.CharField(blank=True, max_length=255)),
                ('task_type', models.CharField(choices=[('object_detection', 'Object Detection'), ('image_classification', 'Image Classification'), ('semantic_segmentation', 'Semantic Segmentation'), ('instance_segmentation', 'Instance Segmentation'), ('keypoint_detection', 'Keypoint Detection')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('is_builtin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_architectures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RunMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField(default=0)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('map50', models.FloatField(blank=True, null=True)),
                ('map75', models.FloatField(blank=True, null=True)),
                ('f1', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.experiment')),
            ],
            options={
                'db_table': 'run_metrics',
                'ordering': ['epoch', 'step'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('hyperparams', models.JSONField(blank=True, default=dict)),
                ('augmentation_config', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.modelarchitecture')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='datasets.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='projects.project')),
            ],
            options={
                'db_table': 'training_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='training.trainingjob'),
        ),
    ]
