# Generated by Django 6.0.1 on 2026-04-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingjob',
            options={'ordering': ['-created_at'], 'permissions': [('start_job', 'Can start a training job'), ('stop_job', 'Can stop a training job')]},
        ),
    ]
